yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path(
        'questions/',
        views.questions,
        name="questions"
    ),
    path(
        'questions/<int:pk>/',
        views.question,
        name="question"
    ),
    path(
        'questions/<int:pk>/visual/',
        views.grath_api,
        name="question_visual"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib import admin
import datetime
from django.utils import timezone

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True, related_name='posts')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments')


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        db_table = 'app_version'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_following')
        ]


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Последние обновления на сайте.
      {% endblock  %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}     
    </header>
    <main>
      <div class="container">
        {% block content %}
        Информация на главной странице будет тут.
        {% endblock %}     
      </div>
    </main>     
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
  {{ post.text|truncatechars:30 }}
{% endblock  %}

{% block content  %}
<div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %} 
              <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_amount }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
              Все посты пользователя
              </a>
            </li>
            </li class="list-group-item ">
              <a href="{% url 'posts:post_edit' post.pk %}"> Редактировать пост </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
          {{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          </p>
        </article>
          {% include 'posts/includes/comments.html' %}
      </div> 
{% endblock  %}

yatube/templates/post_detail_example.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Пост [Фокшаны.] Еще переходъ до Фо…</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: 31 июля 1854
              </li>               
              <li class="list-group-item">
                Группа: Группа: Лев Толстой – зеркало русской революции
                <a href="../posts/group_list.html">
                  все записи группы
                </a>
              </li>            
              <li class="list-group-item">
                Автор: Лев Толстой leo
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >36</span>
              </li>
              <li class="list-group-item">
                <a href="../posts/profile.html">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            <img src="../img/tolstoy.jpg" width="960" height="339" alt="">
            <p>
              [Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ 
              пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно 
              быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и 
              ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится 
              слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. 
              Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. 
              Здоровье кажется (2) лучше.
            </p>
             <!-- эта кнопка видна только автору -->
            <a class="btn btn-primary" href="../posts/update_post.html">
              редактировать запись
            </a>
            <!-- эта форма видна только авторизованному пользователю  -->
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <!-- action ведет на обработчик формы  -->
                <form method="post" action="">
                  <!-- не забываем генерировать токен!  -->
                  <input type="hidden" name="csrfmiddlewaretoken" value="">      
                  <div class="form-group mb-2">
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>

            <!-- комментарии перебираются в цикле  -->

            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="../posts/profile.html">
                    admin
                  </a>
                </h5>
                <p>
                  Монго -- экай чудакъ
                </p>
                </div>
              </div>
              <div class="media mb-4">
                <div class="media-body">
                  <h5 class="mt-0">
                    <a href="../posts/profile.html">
                      admin
                    </a>
                  </h5>
                  <p>
                    Граф - я ваш фанат
                  </p>
                  </div>
                </div>                      
            </article>
        </div>     
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>