yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path(
        'questions/',
        views.questions,
        name="questions"
    ),
    path(
        'questions/<int:pk>/',
        views.question,
        name="question"
    ),
    path(
        'questions/<int:pk>/visual/',
        views.grath_api,
        name="question_visual"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib import admin
import datetime
from django.utils import timezone

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True, related_name='posts')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments')


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        db_table = 'app_version'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_following')
        ]


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

yatube/posts/forms.py
from django import forms
from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Тут будет пост',
            'group': 'А вот тут - группа',
        }
        help_texts = {
            'text': 'Вот прям сюда пиши!',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Сюда комментарий пиши'
        }

yatube/posts/views.py
import json
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.db.models import Sum

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User, Question, Choice


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all().select_related('group')
    paginator = Paginator(post_list, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).select_related('group')
    paginator = Paginator(post_list, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author).select_related('group')
    paginator = Paginator(post_list, settings.PAGINATOR_OBJECTS_PER_PAGchoiE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        if Follow.objects.filter(
           author=author).filter(user=request.user).exists():
            following = True
    template = 'posts/profile.html'
    post_amount = post_list.count()
    context = {
        'author': author,
        'page_obj': page_obj,
        'post_amount': post_amount,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    post_amount = Post.objects.filter(author=post.author).count()
    form = CommentForm()
    context = {
        'post': post,
        'post_amount': post_amount,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    groups = Group.objects.all()
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    context = {
        'groups': groups,
        'form': PostForm()
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user.pk != post.author.pk:
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    groups = Group.objects.all()
    is_edit = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'groups': groups,
        'form': form,
        'is_edit': is_edit,
        'post': post
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        post = get_object_or_404(Post, pk=post_id)
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.PAGINATOR_OBJECTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    post_author = User.objects.get(username=username)
    if request.user != post_author:
        Follow.objects.get_or_create(
            user=request.user,
            author=post_author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(user=request.user).filter(
        author=get_object_or_404(User, username=username)).delete()
    return redirect('posts:profile', username=username)


def questions(request):
    questions_list = Question.objects.all()
    template = 'posts/question_list.html'
    context = {
        'questions_list': questions_list,
    }
    return render(request, template, context)


def question(request, pk):
    if request.method == 'POST':
        result = get_object_or_404(
            Choice, pk=int(request.POST['exampleRadios']))
        result.votes += 1
        result.save()
        return redirect('posts:question_visual', pk=pk)
    question = get_object_or_404(Question, pk=pk)
    choices = Choice.objects.filter(question__id=pk)
    template = 'posts/question.html'
    context = {
        'choices': choices,
        'question': question,
    }
    return render(request, template, context)


def grath_api(request, pk):
    choices = Choice.objects.filter(question__id=pk).values('choice_text', 'votes')
    question = get_object_or_404(Question, pk=pk)
    template = 'posts/grath.html'
    categories = []
    survived_series_data = []
    for entry in choices:
        categories.append(entry['choice_text'])
        survived_series_data.append(int(entry['votes']))
    survived_series = {
        'name': 'Количество голосов',
        'data': survived_series_data,
        'color': 'green'
    }
    chart = {
        'chart': {'type': 'column'},
        'title': {'text': f'Количество голосов в опросе {question.question_text}.'},
        'xAxis': {'categories': categories},
        'series': [survived_series]
    }
    dump = json.dumps(chart)
    return render(request, template, {'chart': dump})

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block  title %}
Новый пост
{% endblock  %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
               {% if is_edit %}
                Редактировать пост
               {% else %}       
                Новый пост
                {% endif %}            
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}"  {% endif %} >
                 {% csrf_token %}          
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form.text.label }}                 
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    {% if is_edit %}
                      {{ post.text }}
                    {% endif %}
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      {{ form.text.help_text }}
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group.label }}                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                    {% for group in groups %}
                      <option value="{{ group.pk }}" selected> {{ group.title }} </option>
                    {% endfor %}
                    <option value="">---------</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      {{ form.group.help_text }}
                    </small>
                  </div>
                  <div class="input-group mb-3">
                    <label class="input-group-text" for="inputGroupFile01">Upload</label>
                    <input type="file" name='image' type="file" class="form-control" id="id_image">
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить
                        {% else %}
                          Добавить
                        {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock  %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
Последние обновления на сайте
{% endblock  %}

{% block content %}
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </p> 
        {% if post.group %}    
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
     {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock  %}

yatube/templates/posts/grath.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
Опросы
{% endblock  %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script>
  Highcharts.chart('container', {{ chart|safe }});
</script>
{% endblock  %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
  Записи сообщества {{ group.title }}
{% endblock  %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </p>    
      </article>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock  %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
Последние обновления на сайте
{% endblock  %}

{% block content %}
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>
          {{ post.text }}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </p> 
        {% if post.group %}    
        <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
        {% endif %}
        <br>
        <a href="{% url 'posts:post_detail' post.id %}">Подробнее</a>
     {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock  %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
Профайл пользователя {{ author.get_full_name }}
{% endblock  %}

{% block content %}
    <div class="container py-5">        
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
  </div>
    {% for post in page_obj %}
    <ul>
        <li>
          Автор: {{ author.get_full_name }}
          <!--<a href="{% url 'posts:profile' user %}">все посты пользователя</a>-->
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>
      {{ post.text }}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    </p>
    {% if post.group %} 
    <p><a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы </a></p>
    {% endif %}    
    <a href="{% url 'posts:post_detail' post.pk %}"> подробная информация </a>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}   
{% endblock  %}

yatube/templates/posts/question.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
Опросы
{% endblock  %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% if choices %}
<div class="container">
    <h4>{{ question.question_text }} </h4>
    <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}"  {% endif %}>
        {% csrf_token %} 
        <ul>
            {% for choice in choices %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value= {{ choice.pk }} checked>
                <label class="form-check-label" for="exampleRadios1">
                {{ choice.choice_text }}
                </label>
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </ul>
    </form>
</div>
{% else %}
    <p>Абшибка</p>
{% endif %}
{% endblock  %}

yatube/templates/posts/question_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block  title %}
Опросы
{% endblock  %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% if questions_list %}
    <ul class="list-group">
        {% for question in questions_list %}
        <li class="list-group-item"> <a href="{% url 'posts:question' question.pk %}">
             {{ question.question_text }}</a>
        </li>
        <br>
        {% endfor %}
    </ul>
{% else %}
    <p>Опросы не найдены.</p>
{% endif %}
{% include 'posts/includes/paginator.html' %}
{% endblock  %}